### ISSUE TITLE
Instructions incomplete or out-of-date ?

### ISSUE THREAD

**Issue by nelsonic** [nlfiedler/elm_base#1]
Hi @nlfiedler thanks for sharing this "base" app with the community! 👍 

I just cloned it and started running the other "setup" commands in "make-sure-it-works" section
https://github.com/nlfiedler/elm_base/tree/675bee2fda4b0c39224d20d3886ec9064913fb38#make-sure-it-works

sadly when I attempt to run `mix test` I get the following error:
```
** (Mix) Could not find migrations directory "priv/repo/migrations"
```
![image](https://user-images.githubusercontent.com/194400/34739641-d6896956-f574-11e7-817e-4c94f3af40a1.png)

Is the app _meant_ to work out-of-the box?
Thanks!

**Comment by nlfiedler** [comment]
Thanks for the report, I've edited the README so it is a little more clear how to use the repo in its current state, and added the `mkdir` that apparently was needed. That's the trouble with not testing the final result with a clean slate. :)

**Comment by nelsonic** [comment]
@nlfiedler nice one. thanks for your prompt reply! 🎉
